-- MySQL Script generated by MySQL Workbench
-- 09/28/14 11:26:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema plotkinm_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `2014Fall_Keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014Fall_Keywords` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TypeId` INT NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2014Fall_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014Fall_Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Name` VARCHAR(45) NOT NULL,
  `Birthday` DATETIME NOT NULL,
  `TypeId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_Keywords_idx` (`TypeId` ASC),
  CONSTRAINT `fk_Users_Keywords`
    FOREIGN KEY (`TypeId`)
    REFERENCES `2014Fall_Keywords` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2014Fall_Food_Eaten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014Fall_Food_Eaten` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Name` VARCHAR(255) NOT NULL,
  `Calories` DECIMAL NOT NULL DEFAULT 0,
  `Fat` DECIMAL NOT NULL DEFAULT 0,
  `Carbs` DECIMAL NOT NULL DEFAULT 0,
  `Fiber` DECIMAL NOT NULL DEFAULT 0,
  `Time` DATETIME NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Food_Eaten_Users1_idx` (`UserId` ASC),
  CONSTRAINT `fk_Food_Eaten_Users1`
    FOREIGN KEY (`UserId`)
    REFERENCES `2014Fall_Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2014Fall_Exercise_Done`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014Fall_Exercise_Done` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TypeId` INT NOT NULL,
  `UserId` INT NOT NULL,
  `Name` VARCHAR(500) NOT NULL,
  `Time` DATETIME NOT NULL,
  `Duration` DECIMAL NOT NULL DEFAULT 0,
  `Intensity` DECIMAL NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_Exercise_Done_Keywords1_idx` (`TypeId` ASC),
  INDEX `fk_Exercise_Done_Users1_idx` (`UserId` ASC),
  CONSTRAINT `fk_Exercise_Done_Keywords1`
    FOREIGN KEY (`TypeId`)
    REFERENCES `2014Fall_Keywords` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exercise_Done_Users1`
    FOREIGN KEY (`UserId`)
    REFERENCES `2014Fall_Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2014Fall_Contact_Methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2014Fall_Contact_Methods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TypeId` INT NOT NULL,
  `UserId` INT NOT NULL,
  `UserName` VARCHAR(255) NOT NULL,
  `Key` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Keywords_Contact_Methods_idx` (`TypeId` ASC),
  INDEX `fk_Contact_Methods_Users1_idx` (`UserId` ASC),
  CONSTRAINT `Keywords_Contact_Methods`
    FOREIGN KEY (`TypeId`)
    REFERENCES `2014Fall_Keywords` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contact_Methods_Users1`
    FOREIGN KEY (`UserId`)
    REFERENCES `2014Fall_Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
